name: env-py2.7-tango9.2.5
channels:
  - tango-controls
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - apipkg=1.5=py27_0
  - atomicwrites=1.3.0=py27_1
  - attrs=19.3.0=py_0
  - backports=1.0=py_2
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - boost=1.67.0=py27_4
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py27_0
  - cffi=1.13.2=py27h2e261b9_0
  - configparser=4.0.2=py27_0
  - contextlib2=0.6.0.post1=py_0
  - execnet=1.7.1=py_0
  - funcsigs=1.0.2=py27_0
  - futures=3.3.0=py27_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - gevent=1.4.0=py27h7b6447c_0
  - greenlet=0.4.15=py27h7b6447c_0
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - icu=58.2=h9c2bf20_1
  - importlib_metadata=1.3.0=py27_0
  - intel-openmp=2019.4=243
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libboost=1.67.0=h46d08c1_4
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py27he904b0f_0
  - mkl_fft=1.0.15=py27ha843d7b_0
  - mkl_random=1.1.0=py27hd6b4f25_0
  - more-itertools=5.0.0=py27_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.5=py27h7e9f1db_0
  - numpy-base=1.16.5=py27hde5b4d6_0
  - omniorb=4.2.2=py27h6bb024c_0
  - openssl=1.1.1d=h7b6447c_3
  - packaging=19.2=py_0
  - pathlib2=2.3.5=py27_0
  - pip=19.3.1=py27_0
  - pluggy=0.13.1=py27_0
  - psutil=5.6.7=py27h7b6447c_0
  - py=1.8.0=py27_0
  - py-boost=1.67.0=py27h04863e7_4
  - pycparser=2.19=py27_0
  - pyparsing=2.4.5=py_0
  - pytest=4.6.2=py27_0
  - pytest-forked=1.1.3=py_0
  - pytest-xdist=1.30.0=py_0
  - python=2.7.17=h9bab390_0
  - readline=7.0=h7b6447c_5
  - scandir=1.10.0=py27h7b6447c_0
  - setuptools=42.0.2=py27_0
  - six=1.13.0=py27_0
  - sqlite=3.30.1=h7b6447c_0
  - tango=9.2.5a=h6bb024c_0
  - tk=8.6.8=hbc83047_0
  - trollius=2.2=py27h14c3975_0
  - wcwidth=0.1.7=py27_0
  - wheel=0.33.6=py27_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
prefix: /opt/conda/envs/env-py2.7-tango9.2.5

